### ISSUE TITLE
Criar telas de interface com usuário

### ISSUE THREAD

**Issue by brenovergilio** [PauloPraf/Cardapium-restaurantes#1]
- **Contexto**: Os requisitos do trabalho de Programação para Dispositivos Móveis exigem algumas telas para funcionalidades obrigatórias.
- **Problema**: É necessária a criação das interfaces do usuário de acordo com os requisitos do trabalho.
- **Solução**: @PauloPraf crie as interfaces necessárias.

**Comment by brenovergilio** [comment]
A tela de cadastro de usuário precisa de um botão para selecionar a foto de perfil e a tela principal do usuário precisa de uma ImageView para mostrar a foto de perfil.

**Comment by PauloPraf** [comment]
Mudanças requisitadas adicionadas ao projeto

**Comment by FelipeSoupinski** [comment]
Foram encontrados problemas de responsividade na tela inicial e na tela de cadastro. Uma sugestão é seguir as recomendações da documentação oficial disponível em: https://developer.android.com/training/constraint-layout?hl=pt-br
