### ISSUE TITLE
Implementação de sistema de login e cadastro.

### ISSUE THREAD

**Issue by PauloPraf** [PauloPraf/Cardapium-restaurantes#2]
Contexto: Os requisitos do trabalho de Programação para Dispositivos Móveis exigem um sistema de login e cadastro de novos usuários.
Problema: É necessária a implementação de um sistemas de login/Criação de usuário com autenticação e mecanismos de prevenção a erros.
Solução: @brenovergilio implemente o sistema de login/cadastro utilizando o firebase às telas já criadas.

**Comment by PauloPraf** [comment]
@brenovergilio  Reparei que esqueceu de implementar a opção do usuário salvar uma foto no seu perfil ao criar a nova conta. 

Este tutorial pode te ajudar:
https://www.youtube.com/watch?v=gqIWrNitbbk&t=32s

**Comment by brenovergilio** [comment]
Falta implementar a verificação da validade do email e senha na tela de cadastro. Você pode usar expressões regulares para isso.

**Comment by PauloPraf** [comment]
Problema resolvido!

**Comment by FelipeSoupinski** [comment]
Eu e o @ryancarloscorrea revisamos a Issue.

Verifiquei que há problemas de responsividade na tela de login. As fontes dos textos não estão de acordo com os princípios de UX. O fundo está claro e a fonte também, o que dificulta a visualização do usuário.

**Comment by ryancarloscorrea** [comment]
Eu verifiquei que a tela de cadastro de usuário não estava responsiva e os TextView não estavam alinhados com os EditText.
