### ISSUE TITLE
Implementar interfaces de cardápio

### ISSUE THREAD

**Issue by FelipeSoupinski** [PauloPraf/Cardapium-restaurantes#4]
- Contexto: Para seguir as regras de negócio da aplicação, afim de ser desenvolvido um mínimo produto viável (MVP), deve ser priorizado a lógica de criação de cardápios.
- Problema: Ainda não foi implementado as interfaces de usuário de cardápios. 
- Solução: @ryancarloscorrea crie as interfaces de criação de cardápios.

**Comment by ryancarloscorrea** [comment]
Interface criada.
Para se criar um cárdapio, é necessário primeiramente criar uma categoria com os campos de nome e imagem, em seguida, adicionar os itens com seus respectivos campos de nome, preço e imagem.

As alterações pode ser encontradas nessa branch  nesse commit: 

https://github.com/PauloPraf/Cardapium-restaurantes/commit/0fde4355b22b63880c05b5520f95ec52fbdd7dd9

**Comment by brenovergilio** [comment]
A cor do botão flutuante precisa ser da palheta de cores definida, atualmente está azul.

**Comment by PauloPraf** [comment]
Reparei também que o atributo margin dos botões não estão simétricos.
