### ISSUE TITLE
Implementar persistência de dados do cardápio

### ISSUE THREAD

**Issue by ryancarloscorrea** [PauloPraf/Cardapium-restaurantes#5]
- Contexto: Afim de implementar as interfaces da criação de cardápio, vou precisar da parte backend de persistência de dados.
- Problema: Ainda não foi implementando a lógica de persistência de dados de cardápio.
- Solução: @FelipeSoupinski Implemente a lógica de persistência de dados.

**Comment by Arakakig** [comment]
É posssível utilizar o Firebase para implementar essa lógica

**Comment by FelipeSoupinski** [comment]
Implementação da persistência de dados de cardápio concluída. As alterações podem ser encontradas nesse commit: 7b716bf62b03becd64d8bc77bfb95fec7585bb70
