### ISSUE TITLE
Criação do README.md

### ISSUE THREAD

**Issue by brenovergilio** [PauloPraf/Cardapium-restaurantes#9]
- Contexto: É importante que todo projeto tenha um arquivo README para que os outros possam saber sua origem e instruções, dentre outras informações.

- Problema: Ainda não foi criado o arquivo README.md

- Solução: @arakakig Crie o arquivo README.md

**Comment by Arakakig** [comment]
Eu e o @FelipeSoupinski revisamos a issue, e verifiquei que foi esquecido de colocar dos Rgas dos alunos

**Comment by FelipeSoupinski** [comment]
Eu verifiquei que faltou descrever as funcionalidades do App.
